
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQpX0HohwKSGAqv_63qzQk1yHOwcRkalQ',
    appId: '1:32642765074:web:5ae7469d150fd0f692e3cb',
    messagingSenderId: '32642765074',
    projectId: 'veena-public-school-app',
    authDomain: 'veena-public-school-app.firebaseapp.com',
    storageBucket: 'veena-public-school-app.firebasestorage.app',
    measurementId: 'G-QLJXPTEBJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQpX0HohwKSGAqv_63qzQk1yHOwcRkalQ',
    appId: '1:32642765074:web:5ae7469d150fd0f692e3cb', // Using Web App ID as fallback, might need specific Android ID
    messagingSenderId: '32642765074',
    projectId: 'veena-public-school-app',
    storageBucket: 'veena-public-school-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQpX0HohwKSGAqv_63qzQk1yHOwcRkalQ',
    appId: '1:32642765074:web:5ae7469d150fd0f692e3cb', // Using Web App ID as fallback
    messagingSenderId: '32642765074',
    projectId: 'veena-public-school-app',
    storageBucket: 'veena-public-school-app.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_YOUR_ID',
    iosBundleId: 'REPLACE_WITH_YOUR_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQpX0HohwKSGAqv_63qzQk1yHOwcRkalQ',
    appId: '1:32642765074:web:5ae7469d150fd0f692e3cb', // Using Web App ID as fallback
    messagingSenderId: '32642765074',
    projectId: 'veena-public-school-app',
    storageBucket: 'veena-public-school-app.firebasestorage.app',
    iosClientId: 'REPLACE_WITH_YOUR_ID',
    iosBundleId: 'REPLACE_WITH_YOUR_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQpX0HohwKSGAqv_63qzQk1yHOwcRkalQ',
    appId: '1:32642765074:web:5ae7469d150fd0f692e3cb', // Using Web App ID as fallback
    messagingSenderId: '32642765074',
    projectId: 'veena-public-school-app',
    storageBucket: 'veena-public-school-app.firebasestorage.app',
    authDomain: 'veena-public-school-app.firebaseapp.com',
  );
}
